<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
  xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" 
  xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="urn:Echo" 
  xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:Echo" name="Echo">
  <wsdl:types>
    <xsd:schema targetNamespace="urn:Echo">
      <xsd:element name="doInvokeNoResponseElements">
        <xsd:complexType>
          <xsd:sequence>
          <xsd:element name="text" type="xsd:string"/>
          </xsd:sequence>
        </xsd:complexType>
      </xsd:element>
      <xsd:element name="doInvokeNoResponseElementsResponse"/>
    </xsd:schema>
  </wsdl:types>
  
  <wsdl:message name="doInvokeNoResponseElementsRequest">
    <wsdl:part element="tns:doInvokeNoResponseElements" name="text"/>
  </wsdl:message>
  <wsdl:message name="doInvokeNoResponseElementsResponse">
    <wsdl:part element="tns:doInvokeNoResponseElementsResponse" name="text"/>
  </wsdl:message>
  <wsdl:portType name="EchoPortType">
    <wsdl:operation name="doInvokeNoResponseElements">
      <wsdl:input message="tns:doInvokeNoResponseElementsRequest" name="doInvokeNoResponseElementsRequest"/>
      <wsdl:output message="tns:doInvokeNoResponseElementsResponse" name="doInvokeNoResponseElementsResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="EchoHttpBinding" type="tns:EchoPortType">
    <wsdlsoap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="doInvokeNoResponseElements">
      <wsdlsoap:operation soapAction=""/>
      <wsdl:input name="doInvokeNoResponseElementsRequest">
        <wsdlsoap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="doInvokeNoResponseElementsResponse">
        <wsdlsoap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Echo">
    <wsdl:port binding="tns:EchoHttpBinding" name="EchoHttpPort">
      <wsdlsoap:address location="http://localhost:8080/xfire/services/Echo"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>